name: Deploy

on: [push]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: bash build.sh

      - name: Install surfer
        run: npm -g install cloudron-surfer

      - shell: bash
        env:
          SURFER_TOKEN: ${{ secrets.SURFER_TOKEN }}
          SURFER_HOST: ${{ secrets.SURFER_HOST }}
          SURFER_FOLDER: ${{ secrets.SURFER_FOLDER }}
        run: |
          echo "$SURFER_FOLDER"

      - name: Upload
        env:
          SURFER_TOKEN: ${{ secrets.SURFER_TOKEN }}
          SURFER_HOST: ${{ secrets.SURFER_HOST }}
          SURFER_FOLDER: ${{ secrets.SURFER_FOLDER }}
        run: surfer put --token "$SURFER_TOKEN" --server "$SURFER_HOST" build/* "$SURFER_FOLDER"/
